### ISSUE TITLE
subject filter is not working ?

### ISSUE THREAD

**Issue by changchichung** [loeffel-io/mail-attachment-downloader#5]
my config.yml
```
imap:
  username: user@abc.com
  password: abc123
  server: mail.abc.com
  port: 993

attachments:
  mimetypes:
    - application/zip
    - image/png
    - text/plain
    - image/jpeg

mails:
  subjects: #[] 
    - invoce, amazon
```

but mail-download still fetch all attachments , no matter what the subject is.
for example , I wrote a mail which subject is Chinese which is obviously not contain the keyword in yml file
but mail-downloader still download the attachment from that mail.
![](https://i.imgur.com/8WUZdkn.png)

**Comment by loeffel-io** [comment]
Hey @changchichung

sorry, never saw this ticket somehow - do you were able to solve this?
Maybe i download all pdfs and only the mails with the filters are converted to pdfs

**Comment by loeffel-io** [comment]
can confirm, attachments dont have subject filters like the yaml shows
ref: https://github.com/loeffel-io/mail-downloader/blob/master/main.go#L125

**Comment by loeffel-io** [comment]
best solution would be to implement search filters for this:

```
imap:
  username: user@abc.com
  password: abc123
  server: mail.abc.com
  port: 993

attachments:
  mimetypes:
    - application/zip
    - image/png
    - text/plain
    - image/jpeg
  subjects: # new 
    - invoice, amazon # new

mails:
  subjects:
    - invoice, amazon
```

even better could be something like this:

```
imap:
  username: user@abc.com
  password: abc123
  server: mail.abc.com
  port: 993

attachments:
  application/zip:
    subjects:
      - invoice, amazon
    filesize: 1-12mb
  image/png
  text/plain
  image/jpeg

mails:
  subjects:
    - invoice, amazon
```
